sudo: required
dist: trusty
language: node_js
node_js:
  - 'node'

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g yarn

before_script:
- npm install

script:
- npm run test -- --watch=false
- yarn lint
- yarn build --base-href https://[ your github username ].github.io/my-awesome-project/


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  target_branch: master
  repo: eentdn/eentdn.github.io
