sudo: required
dist: trusty
language: node_js
node_js:
  - 'node'

services:
  - docker

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install

script:
- npm run test -- --watch=false
- npm run e2e

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    npm run build;
    docker build -t eentdn/roost-angular -f nginx.conf .;
    docker tag eentdn/roost-angular eentdn/roost-angular:$(git rev-parse --short HEAD);
    docker login -u="eentdn13" -p="Een131178";
    docker push eentdn/roost-angular;
    fi
